spring:
  application:
    name: letterboxd-core
  
  # Allow bean definition overriding to resolve conflicts
  main:
    allow-bean-definition-overriding: true
  
  # H2 Database Configuration for Development
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true

# Disable RabbitMQ for development
letterboxd:
  event-hub:
    enabled: false
    retry:
      max-attempts: 3
      delay: 1000
    routing:
      default-exchange: letterboxd.events
      dead-letter-exchange: letterboxd.dlx

# JWT Configuration
jwt:
  secret: mySecretKey
  expiration: 86400

# Application Security JWT Configuration
application:
  security:
    jwt:
      secretKey: mySecretKeyForDevelopmentEnvironment
      expiration: 86400000

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,beans
  endpoint:
    health:
      show-details: always

# Logging Configuration
logging:
  level:
    '[com.uade.tpo.demo]': DEBUG
    '[org.springframework.amqp]': WARN
    '[org.springframework.boot.autoconfigure.amqp]': WARN
