name: Deploy Backend to Elastic Beanstalk

on:
  push:
    branches:
      - main
    paths:
      - 'Back End/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven (prod)
      run: mvn -f "Back End/pom.xml" clean package -Pprod -DskipTests

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: Core-letterboxd
        environment_name: Core-letterboxd-env
        region: us-east-2
        version_label: v-${{ github.sha }}
        version_description: "${{ github.event.head_commit.message }}"
        deployment_package: "Back End/target/core-letterboxd-0.0.1-SNAPSHOT.jar"

